logqueryapi/urls.py
from django.urls import path
from . import views


app_name = 'logqueryapi'
urlpatterns = [
    path('',views.logs_generic,name="generic"),
]

logreader/urls.py
from django.urls import path
from . import views


app_name = 'logreader'
urlpatterns = [
    path('',views.search,name="search"),
    path('logs',views.logs,name="logs")
]

logviewer/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('logreader.urls')),
    path('api/',include('logqueryapi.urls'))
]

logqueryapi/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from . import logreader

def make_query(form):
    # get prams out of requests
    softname=form['soft_name']
    rev_display='reverse_order' in form
    restrict_num='enable_log_num' in form

    # print(rev_display)
    querier=logreader.BasicQuery()
    querier=logreader.SoftQuery(querier,softname)
    # softname_opt=logreader.software_opt(softname)
    querier=querier if not rev_display else logreader.RevQuery(querier)
    # rev_opt=logreader.rev_opt() if rev_display else []
    querier=logreader.RestrictQuery(querier,form['log_num']) if restrict_num else querier


    # print(softname_opt)
    # logs_json=logreader.query_journal(softname_opt+rev_opt+log_num_opt)
    
    return querier.query()

# Create your views here.
def logs_generic(request):
    lst=make_query(request.GET)
    return HttpResponse(json.dumps(lst),charset='utf-8')

logreader/views.py
from django.shortcuts import render
from django.http import Http404,HttpResponse, HttpRequest
from django.urls import reverse
from . import record
import json
import requests
from logqueryapi.views import logs_generic
# Create your views here.

def make_query(form):
    # get prams out of requests
    softname=form['soft_name']
    rev_display='reverse_order' in form
    restrict_num='enable_log_num' in form

    req=requests.get(
        'http://'+'localhost:8000'+reverse("logqueryapi:generic"),
        {"soft_name":softname}
    )

    # querier=logreader.BasicQuery()
    # querier=logreader.SoftQuery(querier,softname)
    # querier=querier if not rev_display else logreader.RevQuery(querier)
    # querier=logreader.RestrictQuery(querier,form['log_num']) if restrict_num else querier
    
    return json.loads(req.text)


def search(request):
    return render(request,"logreader/search.html")

def logs(request):
    # logs_json=make_query(request.GET)
    logs_json=json.loads(logs_generic(request).content)
    msg_list=map(lambda x: (lambda x:(x.get_time(),x.get_msg()))(record.Log(x)),logs_json) 
    return render(request,'logreader/logs.html',{"soft_name":request.GET['soft_name'],"log_list":msg_list})

logreader/templates/logreader/logs.html
<!DOCTYPE html>
<html>

{% load static %}
<head>
    <title>NGC log viewer</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'logreader/logs.css' %}">
</head>

<body>
    <div class="result">
    <h1>Here are logs of <strong>{{ soft_name }}</strong></h1>
    <table>
        <tr>
            <th>time</th>
            <th>message</th>
        </tr>
        {% for t,log in log_list %}
        <tr>
            <td>{{ t.year }}/{{ t.month }}/{{ t.day }} {{t.hour}}:{{t.minute}}:{{t.second}}</td>
            <td>{{ log }}</td>
        </tr>  
        {% endfor%}
    </table>
    </div>
</body>

</html>

logreader/templates/logreader/search.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>NGC log viewer</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'logreader/search.css' %}">
</head>



<body>
    <div class="filter-form">
        <div class="content">
            <h1>Choose your options</h1>
            <form action="{%url 'logreader:logs' %}" method="GET">
                <div class="data-form">
                    <div class="property">
                        <label>software</label>
                        <input type="text" name="soft_name">
                    </div>
                    <div class="property">
                        <input type="checkbox" name="reverse_order">
                        <label>display recent logs first</label>
                    </div>
                    <div class="property">
                        <div>
                            <input type="checkbox" name="enable_log_num">   
                            <label>Restrict number of logs</label>
                        </div>
                        <div>
                        <label>Max log number</label>
                        <input type="number" value=20 name="log_num">
                        </div>
                    </div>
                </div>
                <input type="submit" name="search" class="submit-button">
            </form>
            </div>
    </div>
</body>

</html>